development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: redis://redistogo:60e4e14156c935d9a76c20b4d794bd07@soapfish.redistogo.com:11234/
  channel_prefix: chatroom_production
